# 예외처리

> 요청을 받아서 뿌려주면 끝이나 프론트엔드는 브라우저의 상태라는 것이 있고 상태가 변함에 따라 화면이 변화무쌍하게 변화해야된다.

문법 에러와 같이 프로그래머의 실수로 인해 에러가 발생하는 경우도 있지만, 네트워크 에러와 같이 코드와는 무관한 이유로 발생하는 에러도 있다.

코드 실행중에 에러가 발생하면, 코드의 실행이 중단되어 그 시점에 실행 중이었떤 작업을 완료할수 없다.
JS 는 이로부터 코드의 실행 흐름을 원상복구 할수 있는 기능을 제공하는데 `try..catch..finally` 구문을 사용하면 에러가 나더라도 코드의 흐름을 지속할 수 있다.

```js
try {
  console.log("에러가 나기 직전까지의 코드는 잘 실행됩니다.");
  new Array(-1); // RangeError: Invalid array length
  console.log("에러가 난 이후의 코드는 실행되지 않습니다.");
} catch (e) {
  console.log("코드의 실행 흐름이 catch 블록으로 옮겨집니다.");
  alert(`다음과 같은 에러가 발생했습니다: ${e.name}: ${e.message}`);
}
```

```js
try {
  console.log("에러가 나기 직전까지의 코드는 잘 실행됩니다.");
  new Array(-1); // RangeError: Invalid array length
  console.log("에러가 난 이후의 코드는 실행되지 않습니다.");
} catch (e) {
  if (e.name === "RangeError") {
    alert("배열 생성자에 잘못된 인수가 입력됨");
  } else if (e.name === "ReferenceError") {
    alert("선언되지 않은 변수가 사용됨");
  }
}
```

try 블록은 예외처리를 위해서만 쓰이는 것은 아니다. try 블록 바로 뒤에 finally 블록이 오면, finally 블록에 있는 코드는 try 블록 안에서의 에러 발생 여부와 관계없이 무조건 실행된다. 심지어 try 블록 내에서 returnm break, continue 등으로 인해 코드의 실행 흐름이 즉시 이동될때에도 마찬가지이다.

> finally 안에는 무조건 실행시켜야 하는 것들(로딩인디케이터)

```js
for (let i of [1, 2, 3]) {
  try {
    if (i === 3) {
      break;
    }
  } finally {
    console.log(`현재 i의 값: ${i}`);
  }
}
```

- 에러가 안 났을 때 : try - finally
- 에러가 났을 때 : try - 에러발생 - catch - finally

## 직접 에러 발생시키기

Error 생성자와 throw 구문을 사용해서 프로그래머가 직접 에러를 발생시킬수 있다.

```js
try {
  const even = parseInt(prompt("짝수를 입력하세요"));
  if (even % 2 !== 0) {
    throw new Error("짝수가 아닙니다.");
  }
} catch (e) {
  alert(e.message);
}
```

간혹 프로그램을 작성하면서 에러의 종류를 구분해야 하거나 에러 객체에 기능을 추가해야 할 필요가 있다. 이런 경우에는 Error 를 상속받는 클래스를 만들어서, throw 구문에서 이 클래스를 대신 사용할 수 있다.

예를 들어 아래 MyError 클래스를 통해 에러 객체를 생성할 때 에러에 대한 상세 정보를 포함시키면, catch 블록 안에서 원상복구를 위해 이 값을 활용할 수 있다.

```js
class MyError extends Error {
  constructor(value, ...params) {
    super(...params);
    this.value = value;
    this.name = "MyError";
  }
}

try {
  const even = parseInt(prompt("짝수를 입력하세요"));
  if (even % 2 !== 0) {
    throw new MyError(even, "짝수가 아닙니다.");
  }
} catch (e) {
  if (e instanceof MyError) {
    console.log(e.value);
  }
}
```

## 비동기식 코드에서의 예외처리

**비동기식으로 작동하는 콜백의 내부**에서 발생한 에러는, 콜백 바깥에 있는 try 블록으로는 잡아낼 수 없다.

```js
function add(x, y) {
  new Array(-1);
  return x + y;
}

function add2(x) {
  try {
    return add(x, 2);
  } catch (e) {
    alert("add2 도 잡앗다이놈");
  }
  // `add`를 호출
}

function add2AndPrint(x) {
  try {
    const result = add2(x); // `add2`를 호출
    console.log(result); // `console.log`를 호출
  } catch (e) {
    alert("I caught them");
  }
}
add2AndPrint(3); // `add2AndPrint`를 호출
```

> 비동기 에러는 단순 try catch 문으로 잡을 수 없다

try 블록은 호출 스택이 다 비워진다음에 사용이되면 아무 기능도 못한다.

```js
const buttonEl = document.querySelector("button");

try {
  buttonEl.addEventListener("click", e => {
    try {
      new Array(-1);
      alert("버튼이 눌렸습니다.");
    } catch (e) {
      alert("이벤트 리스너 안에서 에러가 발생했습니다.");
    }
  });
} catch (e) {
  alert("에러가 발생했습니다."); // 출력되지 않음
}
```

## Promise

> 비동기 함수가 진짜 좋은 이유가 try catch 때문이다.

Promeise 객체는 세가지 상태를 가질 수 있다.

- pending - Promise 객체에 결과값이 채워지지 않은 상태
- fulfiled - Promise 객체에 결과값이 채워진 상태
- rejected - Promise 객체에 결과값을 채우려고 시도하다가 에러가 난 상태

```js
const p = new Promise(resolve => {
  const even = parseInt(prompt("짝수를 입력하세요"));
  if (even % 2 !== 0) {
    throw new Error("짝수가 아닙니다.");
  } else {
    resolve(even);
  }
});

p.then(
  even => {
    return "짝수입니다.";
  },
  e => {
    return e.message;
  }
).then(alert);

// 이렇게 도 바꿀수 있다. catch 를 사용해서

p.then(even => {
  return "짝수입니다.";
})
  .catch(e => {
    return e.message;
  })
  .then(alert);
```

> promise 가 복잡한 이유는 비동기 자체가 복잡하고 언어를 바꾸지 않고 기능을 추가하려다 보니깐 너무 어려워짐

> 넘복잡해서 간단하고 깔끔하게 만든게 비동기 프로그래밍

## 비동기 함수

앞의 Promise 객체의 에외 처리 방식은, 일반적인 동기식 예외처리 방식과 다르게 콜백을 사용하고 있어서 코드를 복잡하게 만드는 원인이 된다.
비동기 함수 내부에서, rejected 상태가 된 Promise 객체를 동기식 예외 처리 방식과 동일하게 **try,..catch...finally** 구문으로 처리할 수 있다.

```js
async function func() {
  try {
    const res = await fetch("https://nonexistent-domain.nowhere");
  } catch (e) {
    console.log(e.message);
  }
}

func(); // 출력 결과: Failed to fetch
```

# 모듈

> 한 파일내에 모든것을 짜는 것은 고통스럽다!

최근 들어 프론트엔드 프로젝트의 규모가 커짐에 따라, JavaScript 코드를 여러 파일과 폴더에 나누어 작성하고 서로가 서로를 효율저긍로 불러올 수 있도록 해주는 시스템의 필요성이 절실해 졌다. 이에 따라 모듈 시슽메이 ES2015 에 추가 되었다. script 태그에 type="module" 어트리 뷰트를 추가해주면, 이 파일은 모듈로서 동작한다. 구형 브라우저는 모듈을 지원하지 않는다. 그래서 브라우저 내장 모듈은 사용하지않고 webpack, Parcel 등의 모듈 번들러를 사용한다.

? 웹팩과 파셀의 차이점 : 가장 큰 차이점은 모듈을 하나로 합칠 때 파일들과의 관계를 분석하는 의존성이라고하는데 의존성 분석 방식이 다름 다르다. webpack 는 js 안에있는 import 방식으로 자신이 사용되는 js 를 불러오고 parcel 은 html 파일에서 필요성을 파악한다. 의존성 분석방식이 다르다.

> 모듈 번들러 여러 모듈을 하나의 파일로 합쳐줌 + transfiling(최신문법을 옛날 문법으로 바꾸어줌)

## 모듈이란?

모듈은 기본적으로 Javascript 코드를 담고 있는 파일이다.

- 별다를 처리를 해주지 않아도 엄격모드로 동작
- import, export 구문사용
- 모듈의 가장 바깥쪽에서 선언된 이름은 전역스코프가 아니라 모듈 스코프에서 선언된다.

## 모듈 스코프

모듈 내부의 가장 바깥 스코프에서 이름을 선언하더라도, 전역 스코프가 아니라 모듈 스코프에서 선언된다.

> react 는 undefined, null 을 표현해 주지않는다.

따라서 여러 모듈의 가장 바깥쪽에서 같은 이름으로 변수, 함수, 클래스를 선언하더라도, 서로 다른 스코프에서 선언되기 때문에 이름의 충돌이 생길 일이 없다.

## export & import

> export 수출하다. import 수입하다. 로 이해하고 쉽게 사용해 보자

```js
// variables.js
const foo = "bar";
const spam = "eggs";

// foo, spam을 다른 파일에서 사용할 수 있도록 export 해주었습니다.
export { foo, spam };
```

```js
// main.js

// variables 모듈에 선언된 이름을 사용하기 위해 import 해주었습니다.
import { foo, spam } from "./variables.js";

console.log(foo);
console.log(spam);
```

단순히 값을 저장하고 있는 변수뿐만 아니라, 함수나 클래스도 export 를 통해 여러 모듈에서 재사용할 수 있다.

```js
// functions.js

function add(x, y) {
  return x + y;
}

class Person {
  // ...
}

export { add, Person };
```

다른 모듈에 있는 이름을 사용하려면, 반드시 해당 모듈에서 이름을 export 해주어야 한다. export 해주지 않은 이름을 다른 모듈에서 import 하면 의도대로 동작하지 않을 것이다.

## 선언과 동시에 export 하기

이름을 선언하는 구문 앞에 export 를 붙여주면, 선언과 export 를 한꺼번에 할 수 있다.

```js
export const foo = "bar";
export const spam = "eggs";
export function add(x, y) {
  return x + y;
}
export class person {
  //..
}
```

## default export

모듈을 대표하는 하나의 값을 지정하고 그 `값`을 다른 모듈에서 편하게 불러와서 사용할 수 있다.

import 구문에서 이름을 적어주는 부분에 중괄호를 생략하면, 모듈의 default export 를 가져온다.

export default 뒤에는 임의의 표현식이 올 수 있다. 즉 함수 표현식이나 클래스 표현식도 올수 있다.

```js
// add.js// add.js

  exportexport  defaultdefault  functionfunction ( (x, yx, y) ) {
  {   returnreturn x + y;
} x + y; }
```

```js
import add from "./add.js";

console.log(add(1, 2)); // 3
```

import 구문에서 default export 와 일반적인 export 동시에 가져올 수 있다.

```js
// `React`라는 이름의 default export와,
// Component, Fragment라는 일반적인 export를 동시에 가져오기
import React, { Component, Fragment } from "react";
```

> 이부분이 나에게는 가장 헷갈렷다 나중에 찾아보고 공부한결과 명확해 졌는데 정리해보면
> export default 는 한 모듈에서 하나만 선언이 가능하고 애로 export 할 경우 import 시에 중괄호{}를 붙이지
> 않아도 된다.

## 다른 이름으로 export & import 하기

export 혹은 import 하는 이름의 뒤에 as 를 붙여서, 다른 이름이 대신 사용되게 할 수 있다.

> 모듈에는 하나의 default export 와 여러개의 named export 지정할 수 있다.

## 모듈 사용시 주의할 점

import 구문과 export 구문은 모듈 간 의존 관계를 나타내는 것일뿐, 코드를 실행시키라는 명령이 아니다.

- ECMAScript 공식 명세에는 모듈을 불러오는 방법에 대한 내용이 포함되어 있지않다. 이와 관련된 내용은 전적으로 모듈 구현체에 맡겼다. 따라서, 모듈을 어떤 환경에서 실행하느냐에 따라서 구체적인 로딩순서나 동작 방식이 조금씩 달라 질 수 있다.
- 모듈 번들러는 import 를 하지 않으면 실행시키지 않는다.

# 참고 reperence

[다른 모듈 시스템의 특징과 역사](https://d2.naver.com/helloworld/12864)
